name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: pnpm setup
      uses: pnpm/action-setup
      with:
        version: 8.15.4
    - name: Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: pnpm build
      run: pnpm build