name: Build

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest
    - name: checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
    - name: pnpm setup
      uses: pnpm/action-setup
      with:
        version: 8.15.4
    - name: Rust toolchain
      uses: dtolnay/rust-toolchain
      with:
        toolchain: stable
    - name: Install dependencies
      run: pnpm install
      shell: bash
    - name: pnpm build
      run: pnpm build
      shell: bash